spring.application.name=CURD_API
server.port=8089

spring.datasource.url=jdbc:postgresql://dpg-d2hv8dn5r7bs73es7it0-a.oregon-postgres.render.com:5432/instance_course
spring.datasource.username=instance_course_user
spring.datasource.password=QTIZlN1NRVA9YqbtOz58HPuFEwscf3En
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
